### ISSUE TITLE
MaskKey does not generate the byte `0x00`

### ISSUE THREAD

**Issue by Joannis** [hummingbird-project/hummingbird-websocket#15]
I advice changing the code to generate in the range: `.min ... .max`

https://github.com/hummingbird-project/hummingbird-websocket/blob/3e2e43a599b690008a0c4d53ea765d078c567609/Sources/HummingbirdWSCore/WebSocket.swift#L218

**Comment by adam-fowler** [comment]
Do you want to add a PR for that
