### ISSUE TITLE
RFC 6455(?)

### ISSUE THREAD

**Issue by tannerdsilva** [hummingbird-project/hummingbird-websocket#19]
Hey,

Longtime user of the hummingbird tools here - really appreciate the work and commitment you've given to building this out. Really good stuff. I've used the HTTP server on Linux for many many many months - and was excited to reach for this `hummingbird-websocket` project for a new iOS app I'm writing.

Unfortunately, I've found that in the particular framework doesn't work so well with a lot of the "production" web sockets I'm finding in the wild (in this case, I'm writing a nostr websocket client, similar to [Damus](https://damus.io))

Under my own tight deadlines, and having no firsthand knowledge of the standards behind WebSockets (in the moment), I forked this project and brute forced a problem solving session with GPT-4. Together with this tool, I was able to identify two key ways that this framework is failing in practice.

- On the RFC side, there seems to be some HTTP headers that are not in your current release that certain server sockets expect to see in the "initial request" in order to proceed with an upgrade.

- On the HTTP side, I found a subset of servers are responding with an HTTP redirect code, and the framework is not handling that right now (neither throwing an informative error, nor can it be configured to handle a redirect internally).

The fork I'm currently developing is [here](https://github.com/tannerdsilva/hummingbird-websocket), it's scrappy and not as good looking as the code you write.

For now, just wanted to share the issue and the existence of my fork, which is working better (but not yet perfect) for my particular needs. Pending any possible guidance or feedback from you, I'll open a PR in the next week or two and see if we cant get these changes polished up and merged (if you have an interest in pursuing).

**Comment by adam-fowler** [comment]
Ok Tanner I'll have a look at it tomorrow. I'm guessing the issues you are seeing are all with using the client at the moment. Both of these issue should be resolvable. 

By the way thank you for your support.

**Comment by adam-fowler** [comment]
Ok first issue, the client headers. These are actually correct 
Hummingbird provides the "host" header
NIO provides the "Sec-WebSocket-Key", "Sec-WebSocket-Version", "Connection" and "Upgrade" headers 

I have added PR #20 so you can provide additional headers to initial connect if required, but all standard headers as required by RFC 6455 are added already.

**Comment by adam-fowler** [comment]
#21 adds support to server redirects

**Comment by tannerdsilva** [comment]
Thank you for collaborating with me and providing some prompt feedback and guidance. I look forward to getting these improvements cleaned up and merged into main :) (although it may be a few weeks as my capacity is still limited under tight deadlines to launch my project).

- Upon further investigation of the phenomena I've witness with using your library (and my branch) in my production context, I understand exactly what was leading me to believe `RFC 6455` headers were mis-implemented in your library. I wont be able to fully outline my findings (and solutions) until late this weekend. But I completely agree with you, `RFC 6455` definitely wasn't mis-implemented or buggy. That said, there are still some changes to the upgrade headers that I'd like to propose for #20 that wont break `RFC 6455` compliance. I will update with all those details soon.

- Thank you for providing #21. As I've come to discover, I definitely have a "wild" environment we can test this stuff. Concurrent with the other PR's I'm working on here, I'll be sure to test this on a wide range of server socket implementations and verify the stability.

- Lastly, in #21, I am noticing that you are testing a theoretical (insecure) local url that looks like `ws://<SOME LOCAL IPv4>:8080`. In my own A/B testing of this library with other implementations, I tried connecting hummingbird to a local `nc` TCP listener in my terminal. I found that SwiftNIO will still get caught up in TLS errors even if that `NIOClientTCPBootstrap.enableTLS()` func is never called.

I was able to get around my troubles with a solution that looks like this.

```
static func createBootstrap(url: SplitURL, configuration: Configuration, on eventLoop: EventLoop) throws -> NIOClientTCPBootstrap {
        if let clientBootstrap = ClientBootstrap(validatingGroup: eventLoop) {
            let bootstrap: NIOClientTCPBootstrap
            
            // pass NIOInsecureNoTLS if an insecure URL is provided
            if url.tlsRequired {
                let sslContext = try NIOSSLContext(configuration: configuration.tlsConfiguration)
                let tlsProvider = try NIOSSLClientTLSProvider<ClientBootstrap>(context: sslContext, serverHostname: url.host)
                bootstrap = NIOClientTCPBootstrap(clientBootstrap, tls: tlsProvider)
                bootstrap.enableTLS()
            } else {
                bootstrap = NIOClientTCPBootstrap(clientBootstrap, tls: NIOInsecureNoTLS())
            }
            
            return bootstrap
        }
        preconditionFailure("Failed to create web socket bootstrap")
    }
```

Do you want to create a third PR for this isolated tweak, or should I roll it into one of the existing PR's?

Thanks again for your time and efforts.

**Comment by adam-fowler** [comment]
> I found that SwiftNIO will still get caught up in TLS errors even if that NIOClientTCPBootstrap.enableTLS() func is never called.

What is the exact issue here? I can't see how you used `nc` to test TLS. I guess the change can go through still. I would prefer it in a separate PR though

**Comment by tannerdsilva** [comment]
The TLS issue was a false error (user error on my end).

Apologies for the delay, but I wanted to take the time to make sure I understood the problem completely before throwing down any more info.

I am going to close out this issue, and propose a PR I call the "nostr compatibility update", which is not strictly about RFC 6455, but is related.

Ultimately, I was lead to believe there was an RFC error here since many of the headers dont appear in the code at first glance (they are mostly implemented in NIO), and my own addition of a "Connection":"Upgrade" value in my fork greatly increased compatibility in my application tests. However, we both know, your current release does comply with the spec.

It took some time for me to sort out the solution and validate the changes - but I have it now.

I wont bother explaining all it here. But the changes are all pretty straightforward.

Thanks for engaging with me on this.
