### ISSUE TITLE
Add timeout when closing a WebSocket connection

### ISSUE THREAD

**Issue by Joannis** [hummingbird-project/hummingbird-websocket#46]
> The server MUST close the underlying TCP
   connection immediately; the client SHOULD wait for the server to
   close the connection but MAY close the connection at any time after
   sending and receiving a Close message, e.g., if it has not received a
   TCP Close from the server in a reasonable time period.

I think we're currently not closing the connection at all if a server keeps it open.

**Comment by adam-fowler** [comment]
It is up to the server to initiaite the TCP connection closure. Once it has initiated it, the inbound on the client will finish and the client will close its connection. The RFC is pretty clear the client should not initiate a TCP connection closure
